### ISSUE TITLE
Multiline def-text

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_snippets#1]
@kvichans Made support for mulline def-text //big refactored
I tested on such snip

[class-tst.zip](https://github.com/CudaText-addons/cuda_snippets/files/374451/class-tst.zip)

Try this on other more complex

**Comment by kvichans** [comment]
При применении снипа

```
name=try
id=try
lex=JavaScript
text=
try {
    ${1}
} catch (${2:e}) {
    ${3}
}${4: finally {

}}
```

сбой

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Programs\CudaText\py\cuda_snippets\__init__.py", line 77, in do_menu
    self.do_menu_for_items(items)
  File "C:\Programs\CudaText\py\cuda_snippets\__init__.py", line 73, in do_menu_for_items
    insert_snip_into_editor(ed, items[res][SNIP_TEXT])
  File "C:\Programs\CudaText\py\cuda_snippets\proc_snip_insert.py", line 152, in insert_snip_into_editor
    len_y
TypeError: markers() takes from 2 to 6 positional arguments but 7 were given
```

**Comment by Alexey-T** [comment]
Куда старая -cudatext.py

**Comment by Alexey-T** [comment]
Куд не обновили- *.py

**Comment by Alexey-T** [comment]
сделал API ver check.
