### ISSUE TITLE
error of command "Add"

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_snippets#14]
```
Python 3.8
Init: cuda_console_complete
Loaded session: "history session.json", 0ms, 0 file(s)
Startup: 180ms, plugins: 10ms (console_complete 15ms)
Init: cuda_snippets
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_snippets/__init__.py", line 85, in show_add_snippet
    from cuda_snippets.dlg_snip_manage import DlgSnipMan
  File "/home/user/.config/cudatext/py/cuda_snippets/dlg_snip_manage.py", line 527
    res = ct.msg_box('File modification allowed. Saving file:\n    '+file_dst}, 
                                                                             ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
Init: cudatext
```

@halfbrained

**Comment by halfbrained** [comment]
apologies, fixed https://github.com/halfbrained/cuda_snippets
